name: Sabotage
main: ml.sabotage.Main
version: ${project.version}
api-version: 1.13

authors: ["0-o#9646 ", "AkiraDev"]

softdepend: [PlaceholderAPI, DiscordSRV]
depend: [Config, CorpseImmortal]

permissions:
    zerodasho.sabotage.sabmap:
        default: op
    zerodasho.sabotage.karma:
        default: op
    zerodasho.sabotage.vote:
        default: true
    zerodasho.sabotage.shop:
        default: true
    zerodasho.sabotage.attributes.nohunger:
        default: true
    zerodasho.sabotage.attributes.nodamage:
        default: true
    zerodasho.sabotage.attributes.generic:
        default: true
